<!DOCTYPE html>
<html>
<head>
    <title>CHENG KELO FRESH FISH - All Activities Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; }
        .stat-box { border: 1px solid #ddd; padding: 15px; text-align: center; }
        .stat-number { font-size: 24px; font-weight: bold; color: #2c3e50; }
        .section { margin-bottom: 30px; }
        .section h2 { color: #2c3e50; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        @media print { body { margin: 10px; } }
    </style>
</head>
<body>
    <div class="header">
        <h1>CHENG KELO FRESH FISH</h1>
        <h2>All Activities Report</h2>
        <p>Generated on: {{ $data['report_date'] }}</p>
        <p>Generated by: {{ $data['generated_by'] }}</p>
    </div>

    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_users'] }}</div>
            <div>Total Users</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_categories'] }}</div>
            <div>Fish Categories</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_stock'] }}</div>
            <div>Total Stock</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_sales'] }}</div>
            <div>Total Sold</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{{ $data['remaining_stock'] }}</div>
            <div>Remaining Stock</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">UGX {{ number_format($data['total_sales_amount'], 2) }}</div>
            <div>Total Sales Amount</div>
        </div>
    </div>

    <div class="section">
        <h2>Recent Sales</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Quantity</th>
                    <th>Amount</th>
                    <th>Sold By</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['recent_sales'] as $sale)
                <tr>
                    <td>{{ $sale->sale_date->format('d/m/Y') }}</td>
                    <td>{{ $sale->fishCategory->name }}</td>
                    <td>{{ $sale->quantity }}</td>
                    <td>UGX {{ number_format($sale->total_amount, 2) }}</td>
                    <td>{{ $sale->soldBy->name }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Recent Purchases</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Quantity</th>
                    <th>Cost</th>
                    <th>Supplier</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['recent_purchases'] as $purchase)
                <tr>
                    <td>{{ $purchase->purchase_date->format('d/m/Y') }}</td>
                    <td>{{ $purchase->fishCategory->name }}</td>
                    <td>{{ $purchase->quantity }}</td>
                    <td>UGX {{ number_format($purchase->total_cost, 2) }}</td>
                    <td>{{ $purchase->supplier_name ?? 'N/A' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Pending Stocks</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Quantity</th>
                    <th>Added By</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['pending_stocks'] as $stock)
                <tr>
                    <td>{{ $stock->stock_date->format('d/m/Y') }}</td>
                    <td>{{ $stock->fishCategory->name }}</td>
                    <td>{{ $stock->quantity }}</td>
                    <td>{{ $stock->addedBy->name }}</td>
                    <td>{{ ucfirst($stock->status) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>Generated by CHENG KELO FRESH FISH - {{ now()->format('Y') }}</p>
    </div>
</body>
</html>
