<!DOCTYPE html>
<html>
<head>
    <title>CHENG KELO FRESH FISH - Sales Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; }
        .stat-box { border: 1px solid #ddd; padding: 15px; text-align: center; }
        .stat-number { font-size: 24px; font-weight: bold; color: #2c3e50; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        @media print { body { margin: 10px; } }
    </style>
</head>
<body>
    <div class="header">
        <h1>CHENG KELO FRESH FISH</h1>
        <h2>Sales Report</h2>
        <p>Generated on: {{ $data['report_date'] }}</p>
        <p>Generated by: {{ $data['generated_by'] }}</p>
    </div>

    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_sales'] }}</div>
            <div>Total Quantity Sold</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">UGX {{ number_format($data['total_amount'], 2) }}</div>
            <div>Total Sales Amount</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">UGX {{ number_format($data['today_sales'], 2) }}</div>
            <div>Today's Sales</div>
        </div>
    </div>

    <h2>Sales Details</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total Amount</th>
                <th>Customer</th>
                <th>Sold By</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['sales'] as $sale)
            <tr>
                <td>{{ $sale->sale_date->format('d/m/Y') }}</td>
                <td>{{ $sale->fishCategory->name }}</td>
                <td>{{ $sale->quantity }}</td>
                <td>UGX {{ number_format($sale->unit_price, 2) }}</td>
                <td>UGX {{ number_format($sale->total_amount, 2) }}</td>
                <td>{{ $sale->customer_name ?? 'N/A' }}</td>
                <td>{{ $sale->soldBy->name }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by CHENG KELO FRESH FISH - {{ now()->format('Y') }}</p>
    </div>
</body>
</html>
