<!DOCTYPE html>
<html>
<head>
    <title>CHENG KELO FRESH FISH - Stock Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; }
        .stat-box { border: 1px solid #ddd; padding: 15px; text-align: center; }
        .stat-number { font-size: 24px; font-weight: bold; color: #2c3e50; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .status-approved { color: #27ae60; }
        .status-pending { color: #f39c12; }
        .status-rejected { color: #e74c3c; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        @media print { body { margin: 10px; } }
    </style>
</head>
<body>
    <div class="header">
        <h1>CHENG KELO FRESH FISH</h1>
        <h2>Stock Report</h2>
        <p>Generated on: {{ $data['report_date'] }}</p>
        <p>Generated by: {{ $data['generated_by'] }}</p>
    </div>

    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_approved'] }}</div>
            <div>Approved Stock</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_pending'] }}</div>
            <div>Pending Stock</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{{ $data['total_rejected'] }}</div>
            <div>Rejected Stock</div>
        </div>
    </div>

    <h2>Stock Details</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Cost Price</th>
                <th>Added By</th>
                <th>Approved By</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['stocks'] as $stock)
            <tr>
                <td>{{ $stock->stock_date->format('d/m/Y') }}</td>
                <td>{{ $stock->fishCategory->name }}</td>
                <td>{{ $stock->quantity }}</td>
                <td>UGX {{ number_format($stock->cost_price, 2) }}</td>
                <td>{{ $stock->addedBy->name }}</td>
                <td>{{ $stock->approvedBy ? $stock->approvedBy->name : 'N/A' }}</td>
                <td class="status-{{ $stock->status }}">{{ ucfirst($stock->status) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by CHENG KELO FRESH FISH - {{ now()->format('Y') }}</p>
    </div>
</body>
</html>
